### ISSUE TITLE
Please create separate repositories

### ISSUE THREAD

**Issue by tarsius** [phillord/phil-emacs-packages#1]
Could you please create separate repositories for packages that have nothing to do with one another. That would help users who install packages as git submodules and would also allow me to add the packages to the Emacsmirror. Thanks!

**Comment by phillord** [comment]
Jonas Bernoulli notifications@github.com writes:

> Could you please create separate repositories for packages that have nothing
> to do with one another. That would help users who install packages as git
> submodules and would also allow me to add the packages to the Emacsmirror.
> Thanks!

I've been meaning to do this for a while, but I have to be honest and
admit that's it's not high on my list!

Phil

**Comment by tarsius** [comment]
Take your time.

**Comment by tarsius** [comment]
Since `paredit-menu` is the only package which is currently available from Melpa, I am only really interested in that being available from a separate repository.

I have created a separate branch using

```
$ git branch paredit-menu
$ git filter-branch -f --tree-filter '
git rm -f --ignore-unmatch centering.el eval-pulse.el git-update.el greycite.el leiningen.el omn-mode.el pabbrev.el paredit-pause.el tmmofl.el tmmofl-x.el wide-column.el
' --commit-filter '
test $# = 1 && test -z "$(git ls-tree $1)" && skip_commit "$1" && exit
args="$@"
tree="$1"
shift
while test -n "$1"
do
shift
test "$tree" = $(git rev-parse "$1^{tree}") && map "$1" && exit
shift
done
git commit-tree $args
' paredit-menu
```

(I used my own commit filter because `--prune-empty` isn't quite up to the task.)

I have uploaded the result to https://github.com/tarsius/phil-emacs-packages/tree/paredit-menu.

Please consider creating a new repository from that branch soon.

**Comment by tarsius** [comment]
Let me know if you need any help. I'll also update the Melpa recipe.

**Comment by phillord** [comment]
Thanks! Sorry for being so lazy.

https://github.com/phillord/paredit-menu

I have sent the PR into melpa.

**Comment by tarsius** [comment]
Thanks!

**Comment by phillord** [comment]
Actually, will leave this open to remind me to do the others.

**Comment by tarsius** [comment]
> Actually, will leave this open to remind me to do the others.

Here's a more active reminder: ping!

**Comment by tarsius** [comment]
Ping?

**Comment by tarsius** [comment]
I am closing my old issues.
