### ISSUE TITLE
omn-mode: correct keyword "DisjointUnionOf", add "DifferentIndividuals"

### ISSUE THREAD

**Issue by johanwk** [phillord/phil-emacs-packages#3]
In omn-mode.el, the variable `omn-mode-property-keywords` includes `DisjointUnion`, _but_ the keyword should be `DisjointUnionOf`.

**Comment by phillord** [comment]
Yes, it's missing a few things against the spec. I need to fix it up completely at some point.

I have moved it to it's own repo. It should update on main ELPA soon.
https://github.com/phillord/omn-mode

**Comment by johanwk** [comment]
Thank you so much for the update!

**Comment by phillord** [comment]
It is live on ELPA now, so I will close.
